### ISSUE TITLE
is no longer working

### ISSUE THREAD

**Issue by txd2x** [aaronlam/textnow-autosend#19]
Run node index.js
Start...
User: *** start...
TextNow bot start...
Importing cookies from environment...
Logging in with existing cookies
Failed to log in with existing cookies: Error: Detected invalid or expires cookies
Logging in with account credentials...
Error: No node found for selector: #txt-username
    at Object.assert (/home/runner/work/textnow-autosend/textnow-autosend/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at DOMWorld.type (/home/runner/work/textnow-autosend/textnow-autosend/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:307:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.module.exports.logIn (/home/runner/work/textnow-autosend/textnow-autosend/utils/helper.js:30:5)
    at async actionFunc (/home/runner/work/textnow-autosend/textnow-autosend/index.js:74:17)
    at async /home/runner/work/textnow-autosend/textnow-autosend/index.js:[13](https://github.com/txd2x/textnow-autosend/runs/5965333258?check_suite_focus=true#step:6:13)7:7
Error: Process completed with exit code 1.

**Comment by xyz12810** [comment]
我的也是这样，应该是失效了

**Comment by textkeepa** [comment]
Really cool project—automating TextNow messages has tons of potential! If anyone needs a free U.S. number to test or integrate with, check out [Textnow APK](https://textnowapk.us/) —works well over Wi‑Fi or mobile data.

**Comment by webbrain-one** [comment]
Hi there! 👋

Thanks for the report. It looks like TextNow updated their login page, causing the selector `#txt-username` to fail.

I've opened a pull request to fix this by updating the selectors:
https://github.com/aaronlam/textnow-autosend/pull/20

Let me know if you have any questions! 🚀
